import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import type { NextPage } from "next";
import Head from "next/head";
import UserPost from "~/components/userPost/UserPost";
import { api } from "../utils/api";
import CreatePost from "~/components/createPost/CreatePost";

const FeedPage: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Chatter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="">
          <div>
            {!user.isSignedIn && <SignInButton data-testid='SignInButton' />}
            {user.isSignedIn && <CreatePost />}
          </div>
          <div>{user.isSignedIn && <SignOutButton />}</div>
          <div>
            {data?.map((individualPost) => (
              <UserPost {...individualPost} key={individualPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default FeedPage;
