import { useUser } from "@clerk/nextjs";
import type { NextPage } from "next";
import Head from "next/head";
import UserPost from "~/components/userPost/UserPost";
import { api } from "../utils/api";
import Navbar from "~/components/navbar/Navbar";
import CreatePost from "~/components/createPost/CreatePost";
import { useState, useEffect } from "react";

const FeedPage: NextPage = () => {
  const user = useUser();
  const { data, refetch } = api.posts.getAll.useQuery();
  const [newPostCreated, setNewPostCreated] = useState(false);

  useEffect(() => {
    if (newPostCreated) {
      void refetch();
      setNewPostCreated(false);
    }
  }, [newPostCreated, refetch]);

  return (
    <>
      <Head>
        <title>Chatter - Feed</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="py-869 flex min-h-full items-center justify-center px-4 sm:px-6 lg:px-8">
        <div className="w-full max-w-md space-y-4">
          <div>{user.isSignedIn && <CreatePost onNewPostCreated={setNewPostCreated} />}</div>
          <br />
          {data?.map((individualPost) => (
            <UserPost {...individualPost} key={individualPost.post.id} />
          ))}
        </div>
      </div>
    </>
  );
};

export default FeedPage;
