import { useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import type { NextPage } from "next";
import Head from "next/head";

import { api } from "../utils/api";

import CreatePost from "~/components/CreatePost";


const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();


  return (
    <>
      <Head>
        <title>Chatter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to Chatter
          </h1>
          <p>This application is currently in development</p>
          <div>
            {!user.isSignedIn && <SignInButton />}
            {user.isSignedIn && <CreatePost useUserHook={useUser} />}
          </div>
          <div>{user.isSignedIn && <SignOutButton />}</div>
          <div>
          {data?.map(({ post, author }) => (
            <div key={post.id}>
              <div>Post content: {post.content}</div>
              <div>Author username: {author.username}</div>
              <img src={author.profileImageUrl} alt="author profile image" />
            </div>
          ))}
        </div>

          
        </div>
      </main>
    </>
  );
};

export default Home;
