
import type { NextPage } from "next";
import Head from "next/head";


const PostView: NextPage = () => {



  return (
    <>
      <Head>
        <title>Chatter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
      
      </main>
    </>
  );
};

export default PostView;
